"""Add department table

Revision ID: 2f5516b8e10e
Revises: fcdfb8d30df3
Create Date: 2025-08-24 01:33:18.754773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5516b8e10e'
down_revision: Union[str, Sequence[str], None] = 'fcdfb8d30df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_index(op.f('ix_Department_department_id'), 'Department', ['department_id'], unique=False)
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('school_year', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_Student_id'), 'Student', ['id'], unique=False)
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_Teacher_id'), 'Teacher', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Teacher_id'), table_name='Teacher')
    op.drop_table('Teacher')
    op.drop_index(op.f('ix_Student_id'), table_name='Student')
    op.drop_table('Student')
    op.drop_index(op.f('ix_Department_department_id'), table_name='Department')
    op.drop_table('Department')
    # ### end Alembic commands ###
