"""Fix bug in relationship between record and session

Revision ID: 4d935e19ffb9
Revises: 6ef785d5b1ce
Create Date: 2025-08-25 00:35:41.466431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d935e19ffb9'
down_revision: Union[str, Sequence[str], None] = '6ef785d5b1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Record', sa.Column('session_id', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('Record_teacher_id_fkey'), 'Record', type_='foreignkey')
    op.drop_constraint(op.f('Record_class_id_fkey'), 'Record', type_='foreignkey')
    op.create_foreign_key(None, 'Record', 'Session', ['session_id'], ['session_id'])
    op.drop_column('Record', 'end_time')
    op.drop_column('Record', 'class_id')
    op.drop_column('Record', 'teacher_id')
    op.drop_column('Record', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Record', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Record', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Record', sa.Column('class_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('Record', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Record', type_='foreignkey')
    op.create_foreign_key(op.f('Record_class_id_fkey'), 'Record', 'Class', ['class_id'], ['class_id'])
    op.create_foreign_key(op.f('Record_teacher_id_fkey'), 'Record', 'Teacher', ['teacher_id'], ['id'])
    op.drop_column('Record', 'session_id')
    # ### end Alembic commands ###
