"""Make change in Class model: change datatype of year from DATE to INT

Revision ID: 6ef785d5b1ce
Revises: d5883e3b7dc8
Create Date: 2025-08-24 13:03:53.973489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef785d5b1ce'
down_revision: Union[str, Sequence[str], None] = 'd5883e3b7dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Class',
        'year',
        type_=sa.Integer(),
        postgresql_using="EXTRACT(YEAR FROM year)::INTEGER"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Class',
        'year',
        type_=sa.Date(),
        postgresql_using="TO_DATE(year::text, 'YYYY')"
    )
    # ### end Alembic commands ###
