"""change datatype of record

Revision ID: 90d4a05d8f19
Revises: ae9b12ec8e0e
Create Date: 2025-08-29 19:29:21.583072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d4a05d8f19'
down_revision: Union[str, Sequence[str], None] = 'ae9b12ec8e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Record_record_id'), 'Record', ['record_id'], unique=False)
    op.alter_column('Record', 'student_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('Record', 'record_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
