"""Fully create the db schema

Revision ID: 99f4de0b48b8
Revises: 2f5516b8e10e
Create Date: 2025-08-24 01:46:13.215077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f4de0b48b8'
down_revision: Union[str, Sequence[str], None] = '2f5516b8e10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'User', 'Department', ['department_id'], ['department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    # ### end Alembic commands ###
