"""Change teacher_id in Session to String

Revision ID: ae9b12ec8e0e
Revises: 4d935e19ffb9
Create Date: 2025-08-25 01:18:09.584314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9b12ec8e0e'
down_revision: Union[str, Sequence[str], None] = '4d935e19ffb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Session_teacher_id_fkey', 'Session', type_='foreignkey')
    op.alter_column('Session', 'teacher_id', type_=sa.String(length=255))
    op.create_foreign_key(
        'Session_teacher_id_fkey',
        'Session', 'Teacher',
        ['teacher_id'], ['teacher_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Session_teacher_id_fkey', 'Session', type_='foreignkey')
    op.alter_column('Session', 'teacher_id', type_=sa.Integer())
    op.create_foreign_key(
        'Session_teacher_id_fkey',
        'Session', 'Teacher',
        ['teacher_id'], ['id']
    )
    # ### end Alembic commands ###
