"""Add Course and record table

Revision ID: d5883e3b7dc8
Revises: 99f4de0b48b8
Create Date: 2025-08-24 02:29:00.381337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5883e3b7dc8'
down_revision: Union[str, Sequence[str], None] = '99f4de0b48b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
    sa.Column('course_id', sa.String(length=255), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['Department.department_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_Course_course_id'), 'Course', ['course_id'], unique=False)
    op.create_table('Class',
    sa.Column('class_id', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_Class_class_id'), 'Class', ['class_id'], unique=False)
    op.create_table('Record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('class_id', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_Record_record_id'), 'Record', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Record_record_id'), table_name='Record')
    op.drop_table('Record')
    op.drop_index(op.f('ix_Class_class_id'), table_name='Class')
    op.drop_table('Class')
    op.drop_index(op.f('ix_Course_course_id'), table_name='Course')
    op.drop_table('Course')
    # ### end Alembic commands ###
