INSERT INTO "Course" (course_id, course_name, department_id) 
VALUES
    ('CS101', 'Introduction to Computer Science', 'MCS'),
    ('CS102', 'Data Structures', 'MCS'),
    ('CS103', 'Algorithms', 'MCS'),
    ('IT101', 'Information Technology Basics', 'FIT'),
    ('IT102', 'Web Development', 'FIT'),
    ('IT103', 'Database Management', 'FIT'),
    ('PH101', 'Physics I', 'PHYS'),
    ('PH102', 'Physics II', 'PHYS'),
    ('PH103', 'Engineering Physics', 'PHYS'),
    ('EE101', 'Circuit Analysis', 'FETEL'),
    ('EE102', 'Digital Systems', 'FETEL'),
    ('EE103', 'Microprocessors', 'FETEL'),
    ('CHEM101', 'General Chemistry', 'CHEM'),
    ('CHEM102', 'Organic Chemistry', 'CHEM'),
    ('CHEM103', 'Physical Chemistry', 'CHEM'),
    ('BIO101', 'General Biology', 'FBB'),
    ('BIO102', 'Genetics', 'FBB'),
    ('BIO103', 'Microbiology', 'FBB'),
    ('ENV101', 'Environmental Science', 'ENV'),
    ('ENV102', 'Sustainable Development', 'ENV'),
    ('ENV103', 'Ecology', 'ENV'),
    ('GEO101', 'Physical Geography', 'GEO'),
    ('GEO102', 'Human Geography', 'GEO'),
    ('GEO103', 'Geographic Information Systems', 'GEO'),
    ('MST101', 'Materials Science', 'MST'),
    ('MST102', 'Nanotechnology', 'MST'),
    ('MST103', 'Polymer Science', 'MST'),
    ('FIS101', 'Interdisciplinary Science', 'FIS'),
    ('FIS102', 'Science and Society', 'FIS'),
    ('FIS103', 'Research Methods', 'FIS');
