name: CI

on:
  push:
    branches: [ main, thuanlv/Model_create ]
  pull_request:
    branches: [ main, thuanlv/Model_create ]

env:
  APP_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"   # cache dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest testcontainers psycopg2-binary  # đảm bảo có lib test

      - name: Verify Docker is available
        run: docker ps

      - name: Run pytest
        run: pytest --maxfail=3 --disable-warnings -q
